### ISSUE TITLE
Make port type configurable

### ISSUE THREAD

**Issue by Volinger** [fieldrndservices/libssh2-labview#43]
Hello, 

would it be possible to change Session/connect.vi VI, or add some other with the same functionality, which would allow to use other port for SSH than 22? Currently it is hardcoded as I can see and I dont see any way in the toolkit, which would allow me to select the SSH port.
Here is what I suggest:
Before:
![image](https://user-images.githubusercontent.com/74205481/144423396-272fbdb9-d24a-46fd-a3b2-1d8828f312df.png)
After:
![image](https://user-images.githubusercontent.com/74205481/144423625-2e28a413-0dc3-4469-90a5-a57d0fcf526a.png)

**Comment by volks73** [comment]
Looks good to me and makes perfect sense. I would add it to the connector pane of the VI at the bottom between the Error In and Error Out terminals and make it optional with a default of 22, which should be next to the Timeout terminal.

**Comment by Volinger** [comment]
Thank you, shall I update it or will you do it please? I tried to, since you assigned the issue to me, but I think I need some rights to the repository to push the code and create and create a pull request if I am not mistaken : )

**Comment by volks73** [comment]
I have gone ahead and made the change to the Connect VI. This should be available as of 18100aeeca013c3a8bc970b98ff88c68b69ef333.

I am closing this issue, but it may be while before I create a new release. However, this change is available from the source code by cloning this repository (`git clone https://github.com/fieldrndservices/libssh2-labview.git`). You should be able to clone the repository. If you cannot, then please let me know.

For future reference, the conventional process for contributing code would be fork this repository within GitHub, clone your forked repository within your user account onto your local development machine, modify the code, commit changes, push changes to your forked repository, and then submit a Pull Request. I think you may have run into some permissions issue because you were trying to submit PR directly from a clone of this repository instead of a fork. Note, a GitHub "fork" is not necessarily the same thing as a "hard" fork. PR submission to this repository does require write access from the maintainer.
