### ISSUE TITLE
SSH : two CMD in same channel

### ISSUE THREAD

**Issue by Clio75** [fieldrndservices/libssh2-labview#5]
Hi, I tried to send more that one CMD into the Channel I had created. 
![image](https://user-images.githubusercontent.com/8381796/77686950-fe95cc00-6f9d-11ea-8b15-b1cc64cce71f.png)

But It return:
Field_RnD_Services_LIBSSH2_Toolkit.lvlib:Check Status.vi<ERR>
[Bad Use Error]
![image](https://user-images.githubusercontent.com/8381796/77687004-14a38c80-6f9e-11ea-8af4-2091c0e6a51d.png)

Do I need to wait or do something between CMD ?

**Comment by volks73** [comment]
I think the Execute VI, and its underlying libssh2 function ([`libssh2_channel_exec`](https://www.libssh2.org/libssh2_channel_exec.html)) is an "execute once and get out" kind of function. In other words, it can only be used once per session/channel. See [Execute multiple commands sequentially with libssh2](https://stackoverflow.com/questions/58775197/execute-multiple-commands-sequentially-with-libssh2) on StackOverflow, as it is identical to your error but for C instead of LabVIEW. There is unfortunately no answer or resolution, but it provides evidence that the you cannot use the Execute VI twice on the same session/channel.

[Discussion on the libssh2 mailing list](https://www.libssh2.org/mail/libssh2-devel-archive-2010-01/0107.shtml) also indicates the channel must be destroyed/closed before another Execute can be used. 

So, I think you have a couple of options: (1) Create/Open and Destroy/Close a channel for each Execute or (2) investigate using the Shell VI,  with the Write All VI.

Option 2 actually looks like the appropriate implementation based on the [`ssh2.c`](https://www.libssh2.org/examples/ssh2.html) example, but I have never really used the Shell VI. Here is a totally untested and probably does not work example:

![Send Multiple Commands Example v1](https://user-images.githubusercontent.com/1915469/77693967-a18b1d80-6f7f-11ea-89a1-f662c8d0bbf7.png)

**Comment by Clio75** [comment]
I will investigate to use the shell option. I will let you know the result

**Comment by volks73** [comment]
@Clio75, FYI, I created a new release (Alpha-2.0) that includes an example for the single command execution and the fixes for the palettes. If you get a working example of the Shell option, I will add it to the Examples and include in the next release.

**Comment by Clio75** [comment]
With the VIP-1-0-0-15 pallet I have tested this: One channel for each CMD: 
![image](https://user-images.githubusercontent.com/8381796/77949555-6febbc80-72c7-11ea-9911-ec218d05e73e.png)
And it executing perfect. 

But also this works; One channel for BOTH CMD: 
![image](https://user-images.githubusercontent.com/8381796/77949822-dffa4280-72c7-11ea-8fa8-5697f5b8b0e9.png)

**Comment by volks73** [comment]
Great! I will create some examples based on these screenshots and include them in the next release. I will probably not include them as usage examples in the README as those are meant to be quick, simple examples of doing one thing. These feel a little more complex, or something to look at after trying one of the usage examples.

I think this means this issue is resolved.
